import type {
  EditorialLayoutBlock,
  EditorialTemplate,
  EditorialTemplateFormatProfile,
  EditorialTemplateInputSpec,
} from "../types/editorialTemplate";
import { sortTemplatesByPriority, USER_FACING_PLACEHOLDERS } from "./editorialTemplateUtils";

const input = (key: string, label: string, placeholder?: string, description?: string): EditorialTemplateInputSpec => ({
  key,
  label,
  placeholder,
  description,
});

const block = (
  id: string,
  type: EditorialLayoutBlock["type"],
  label: string,
  placeholder: string,
  contentHint?: string,
  required = true,
): EditorialLayoutBlock => ({ id, type, label, placeholder, contentHint, required });

const titleBlock = block("title", "title", "Tiêu đề", USER_FACING_PLACEHOLDERS.title, "Nêu ngắn gọn chủ đề chính.");
const sourceBlock = block("source_note", "source_note", "Nguồn/căn cứ", USER_FACING_PLACEHOLDERS.source, "Ghi nguồn thông tin hoặc căn cứ sử dụng.", false);
const verifyBlock = block("verification", "review_note", "Điểm cần xác minh", USER_FACING_PLACEHOLDERS.verify, "Liệt kê nội dung còn cần kiểm tra.", false);

const administrativeFormatProfile: EditorialTemplateFormatProfile = {
  paper: "A4",
  fontFamily: "Times New Roman",
  bodyFontSize: 14,
  tableFontSize: 13,
  noteFontSize: 12,
  bodyLineHeight: 1.5,
  tableLineHeight: 1.15,
  noteItalic: true,
  tableHeaderBold: true,
  tableBorder: "black",
  tableBackground: "white",
  tableCaptionPosition: "above",
  figureCaptionPosition: "below",
  firstLineIndent: "Gợi ý thụt dòng đầu đoạn 1cm hoặc theo quy định nội bộ.",
  paragraphSpacingBefore: "Gợi ý 0pt trước đoạn.",
  paragraphSpacingAfter: "Gợi ý 6pt sau đoạn khi cần tăng độ đọc.",
  margins: {
    top: "20-25mm",
    right: "15-20mm",
    bottom: "20-25mm",
    left: "30-35mm",
  },
  notes: ["Chỉ là metadata định dạng cho bước tích hợp sau; PR này không áp dụng vào export."],
};

const communicationInputs = [
  input("topic", "Chủ đề/nội dung chính", USER_FACING_PLACEHOLDERS.verify),
  input("audience", "Đối tượng độc giả", USER_FACING_PLACEHOLDERS.verify),
];

const administrativeInputs = [
  input("title", "Tên văn bản/nội dung chính", USER_FACING_PLACEHOLDERS.title),
  input("legalBasis", "Căn cứ pháp lý hoặc căn cứ triển khai", USER_FACING_PLACEHOLDERS.legalBasis),
  input("recipient", "Nơi nhận/đơn vị liên quan", USER_FACING_PLACEHOLDERS.recipient),
];

const reviewInputs = [
  input("draftText", "Nội dung cần xử lý", USER_FACING_PLACEHOLDERS.verify),
];

const editorialTemplates: EditorialTemplate[] = [
  {
    id: "website_article_basic",
    name: "Bài website cơ bản",
    group: "communication_content",
    category: "website_article",
    description: "Khung bài đăng website rõ tiêu đề, mở đầu, thân bài và kết luận.",
    useCases: ["Đăng website đơn vị", "Giới thiệu hoạt động", "Truyền thông nội bộ"],
    requiredInputs: communicationInputs,
    optionalInputs: [input("source", "Nguồn thông tin", USER_FACING_PLACEHOLDERS.source), input("image", "Ảnh minh họa", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("lead", "lead", "Mở đầu/sapo", USER_FACING_PLACEHOLDERS.verify), block("body", "section", "Nội dung chính", USER_FACING_PLACEHOLDERS.data), sourceBlock, block("conclusion", "paragraph", "Kết luận/định hướng", USER_FACING_PLACEHOLDERS.conclusion, "Chốt thông điệp chính.", false)],
    preflightHints: ["Kiểm tra tiêu đề và sapo có phản ánh đúng nội dung.", "Bổ sung nguồn cho số liệu hoặc nhận định quan trọng."],
    tags: ["website", "bài viết", "truyền thông"],
    priority: 90,
    isOfficialStyleSupported: false,
  },
  {
    id: "news_article_basic",
    name: "Tin tức cơ bản",
    group: "communication_content",
    category: "news_article",
    description: "Khung tin tức theo sự kiện, có thời gian, địa điểm, diễn biến và nguồn.",
    useCases: ["Tin sự kiện", "Tin hoạt động", "Tin cập nhật nhanh"],
    requiredInputs: [input("event", "Sự kiện/hoạt động", USER_FACING_PLACEHOLDERS.verify), input("timePlace", "Thời gian, địa điểm", USER_FACING_PLACEHOLDERS.verify)],
    optionalInputs: [input("participants", "Đơn vị/cá nhân tham gia", USER_FACING_PLACEHOLDERS.verify), input("source", "Nguồn tin", USER_FACING_PLACEHOLDERS.source)],
    layoutBlocks: [titleBlock, block("dateline", "metadata", "Thời gian, địa điểm", USER_FACING_PLACEHOLDERS.verify), block("lead", "lead", "Thông tin nổi bật", USER_FACING_PLACEHOLDERS.verify), block("details", "section", "Diễn biến chính", USER_FACING_PLACEHOLDERS.data), sourceBlock],
    preflightHints: ["Xác minh thời gian, địa điểm và tên đơn vị.", "Không đưa nhận định chưa có nguồn."],
    tags: ["tin tức", "sự kiện", "hoạt động"],
    priority: 88,
    isOfficialStyleSupported: false,
  },
  {
    id: "company_intro_article",
    name: "Bài giới thiệu công ty/đơn vị",
    group: "communication_content",
    category: "intro_article",
    description: "Khung giới thiệu năng lực, lịch sử, giá trị và điểm nổi bật của đơn vị.",
    useCases: ["Giới thiệu công ty", "Giới thiệu đơn vị", "Trang hồ sơ năng lực"],
    requiredInputs: [input("entityName", "Tên công ty/đơn vị", USER_FACING_PLACEHOLDERS.verify), input("strengths", "Điểm mạnh chính", USER_FACING_PLACEHOLDERS.data)],
    optionalInputs: [input("history", "Lịch sử/hành trình", USER_FACING_PLACEHOLDERS.verify), input("certifications", "Chứng nhận/thành tích", USER_FACING_PLACEHOLDERS.source)],
    layoutBlocks: [titleBlock, block("overview", "lead", "Tổng quan", USER_FACING_PLACEHOLDERS.verify), block("mission", "section", "Sứ mệnh/giá trị", USER_FACING_PLACEHOLDERS.verify), block("capability", "section", "Năng lực nổi bật", USER_FACING_PLACEHOLDERS.data), sourceBlock],
    preflightHints: ["Kiểm tra số liệu năng lực và thành tích có nguồn.", "Tránh dùng tuyên bố quá mức khi chưa xác minh."],
    tags: ["giới thiệu công ty", "hồ sơ", "website"],
    priority: 86,
    isOfficialStyleSupported: false,
  },
  {
    id: "activity_report_article",
    name: "Bài phản ánh hoạt động",
    group: "communication_content",
    category: "activity_report",
    description: "Khung bài phản ánh hoạt động có bối cảnh, kết quả và hình ảnh minh họa.",
    useCases: ["Tổng thuật hoạt động", "Bài sau sự kiện", "Bản tin nội bộ"],
    requiredInputs: [input("activity", "Tên hoạt động", USER_FACING_PLACEHOLDERS.verify), input("result", "Kết quả nổi bật", USER_FACING_PLACEHOLDERS.data)],
    optionalInputs: [input("participants", "Người tham gia", USER_FACING_PLACEHOLDERS.verify), input("imageCaption", "Chú thích ảnh", USER_FACING_PLACEHOLDERS.source)],
    layoutBlocks: [titleBlock, block("context", "lead", "Bối cảnh hoạt động", USER_FACING_PLACEHOLDERS.verify), block("result", "section", "Kết quả chính", USER_FACING_PLACEHOLDERS.data), block("figure", "figure_placeholder", "Ảnh minh họa", USER_FACING_PLACEHOLDERS.source, "Giữ ảnh và chú thích thành một nhóm semantic.", false), sourceBlock],
    preflightHints: ["Bổ sung số liệu kết quả nếu có.", "Kiểm tra chú thích ảnh không trùng tiêu đề."],
    tags: ["hoạt động", "sự kiện", "bài phản ánh"],
    priority: 84,
    isOfficialStyleSupported: false,
  },
  {
    id: "website_feature_article",
    name: "Bài chuyên đề website",
    group: "communication_content",
    category: "feature_article",
    description: "Khung bài chuyên đề có luận điểm, dẫn chứng và kết luận định hướng.",
    useCases: ["Bài phân tích nhẹ", "Bài chuyên đề website", "Bài truyền thông dài"],
    requiredInputs: [input("topic", "Chủ đề chuyên đề", USER_FACING_PLACEHOLDERS.verify), input("keyPoints", "Luận điểm chính", USER_FACING_PLACEHOLDERS.data)],
    optionalInputs: [input("sources", "Nguồn/dẫn chứng", USER_FACING_PLACEHOLDERS.source), input("quote", "Trích dẫn", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("lead", "lead", "Góc tiếp cận", USER_FACING_PLACEHOLDERS.verify), block("argument", "section", "Luận điểm và dẫn chứng", USER_FACING_PLACEHOLDERS.source), block("quote", "quote", "Trích dẫn", USER_FACING_PLACEHOLDERS.verify, undefined, false), block("conclusion", "paragraph", "Kết luận", USER_FACING_PLACEHOLDERS.conclusion)],
    preflightHints: ["Kiểm tra luận điểm có đủ dẫn chứng.", "Đánh dấu nội dung cần xác minh trước khi đăng."],
    tags: ["chuyên đề", "website", "phân tích"],
    priority: 80,
    isOfficialStyleSupported: false,
  },
  {
    id: "language_review",
    name: "Rà soát ngôn ngữ",
    group: "review_improvement",
    category: "review",
    description: "Khung kiểm tra chính tả, diễn đạt, thuật ngữ và độ rõ ràng.",
    useCases: ["Rà soát chính tả", "Sửa lỗi văn phong", "Chuẩn hóa câu chữ"],
    requiredInputs: reviewInputs,
    optionalInputs: [input("styleGuide", "Yêu cầu văn phong", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [block("scope", "metadata", "Phạm vi rà soát", USER_FACING_PLACEHOLDERS.verify), block("issues", "checklist", "Danh sách lỗi cần xử lý", USER_FACING_PLACEHOLDERS.verify), block("suggestions", "review_note", "Gợi ý chỉnh sửa", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Chỉ đề xuất, không tự ghi đè nội dung gốc.", "Phân biệt lỗi chắc chắn và điểm cần người dùng xác minh."],
    tags: ["rà soát chính tả", "văn phong", "sửa lỗi"],
    priority: 78,
    isOfficialStyleSupported: false,
  },
  {
    id: "argument_strengthening",
    name: "Củng cố lập luận",
    group: "review_improvement",
    category: "improvement",
    description: "Khung nhận diện luận điểm yếu, thiếu dẫn chứng và đề xuất tăng sức thuyết phục.",
    useCases: ["Củng cố lập luận", "Rà soát logic", "Tăng tính thuyết phục"],
    requiredInputs: reviewInputs,
    optionalInputs: [input("evidence", "Dẫn chứng hiện có", USER_FACING_PLACEHOLDERS.source)],
    layoutBlocks: [block("claims", "checklist", "Luận điểm chính", USER_FACING_PLACEHOLDERS.verify), block("evidence", "review_note", "Dẫn chứng cần bổ sung", USER_FACING_PLACEHOLDERS.source), verifyBlock],
    preflightHints: ["Không tự bịa dẫn chứng.", "Đánh dấu nơi cần bổ sung số liệu hoặc nguồn."],
    tags: ["lập luận", "dẫn chứng", "phản biện"],
    priority: 70,
    isOfficialStyleSupported: false,
  },
  {
    id: "source_checking",
    name: "Kiểm tra nguồn và căn cứ",
    group: "review_improvement",
    category: "source_check",
    description: "Khung rà soát đoạn thiếu nguồn, thiếu căn cứ hoặc cần xác minh.",
    useCases: ["Kiểm tra nguồn", "Rà căn cứ pháp lý", "Đánh dấu nội dung cần xác minh"],
    requiredInputs: reviewInputs,
    optionalInputs: [input("sourceList", "Danh sách nguồn", USER_FACING_PLACEHOLDERS.source)],
    layoutBlocks: [block("source_inventory", "checklist", "Nguồn hiện có", USER_FACING_PLACEHOLDERS.source), block("missing_sources", "review_note", "Nội dung thiếu nguồn", USER_FACING_PLACEHOLDERS.source), verifyBlock],
    preflightHints: ["Tách rõ thiếu nguồn và chưa xác minh.", "Không coi placeholder là nguồn hợp lệ."],
    tags: ["nguồn", "căn cứ", "xác minh"],
    priority: 72,
    isOfficialStyleSupported: false,
  },
  {
    id: "summary_rewrite",
    name: "Tóm tắt/viết lại có kiểm soát",
    group: "review_improvement",
    category: "rewrite",
    description: "Khung chuẩn bị tóm tắt hoặc viết lại dựa trên nội dung người dùng cung cấp.",
    useCases: ["Tóm tắt", "Viết lại ngắn gọn", "Chuẩn hóa bản nháp"],
    requiredInputs: reviewInputs,
    optionalInputs: [input("targetLength", "Độ dài mong muốn", USER_FACING_PLACEHOLDERS.verify), input("audience", "Đối tượng đọc", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [block("summary_goal", "metadata", "Mục tiêu tóm tắt/viết lại", USER_FACING_PLACEHOLDERS.verify), block("key_points", "list", "Ý chính cần giữ", USER_FACING_PLACEHOLDERS.verify), block("constraints", "review_note", "Ràng buộc cần lưu ý", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Không tạo nội dung mới ngoài dữ liệu đầu vào.", "Đánh dấu phần thiếu dữ liệu thay vì suy đoán."],
    tags: ["tóm tắt", "viết lại", "rút gọn"],
    priority: 68,
    isOfficialStyleSupported: false,
  },
  {
    id: "website_style_polish",
    name: "Chỉnh văn phong website",
    group: "review_improvement",
    category: "improvement",
    description: "Khung cải thiện độ mạch lạc và phù hợp phong cách website.",
    useCases: ["Làm mượt bài website", "Tối ưu nhịp đọc", "Chuẩn hóa giọng truyền thông"],
    requiredInputs: reviewInputs,
    optionalInputs: [input("brandTone", "Giọng thương hiệu", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [block("tone", "metadata", "Giọng văn mục tiêu", USER_FACING_PLACEHOLDERS.verify), block("readability", "checklist", "Điểm cần làm rõ", USER_FACING_PLACEHOLDERS.verify), block("polish_notes", "review_note", "Gợi ý chỉnh văn", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Không làm thay đổi thông tin cốt lõi.", "Giữ đề xuất ở dạng preview để người dùng Apply/Cancel ở PR tích hợp sau."],
    tags: ["website", "văn phong", "polish"],
    priority: 66,
    isOfficialStyleSupported: false,
  },
  {
    id: "official_report_basic",
    name: "Báo cáo hành chính cơ bản",
    group: "administrative_document",
    category: "official_report",
    description: "Khung báo cáo có căn cứ, tình hình, kết quả, tồn tại và kiến nghị.",
    useCases: ["Báo cáo", "Tổng kết", "Sơ kết", "Báo cáo hành chính"],
    requiredInputs: administrativeInputs,
    optionalInputs: [input("data", "Số liệu/kết quả", USER_FACING_PLACEHOLDERS.data), input("recommendation", "Kiến nghị", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("legal_basis", "legal_basis", "Căn cứ", USER_FACING_PLACEHOLDERS.legalBasis), block("situation", "section", "Tình hình chung", USER_FACING_PLACEHOLDERS.data), block("results", "section", "Kết quả đạt được", USER_FACING_PLACEHOLDERS.data), block("limitations", "section", "Tồn tại, nguyên nhân", USER_FACING_PLACEHOLDERS.verify), block("recommendations", "section", "Kiến nghị/đề xuất", USER_FACING_PLACEHOLDERS.verify), block("signature", "signature", "Ký tên", USER_FACING_PLACEHOLDERS.verify, undefined, false)],
    preflightHints: ["Bổ sung căn cứ pháp lý nếu văn bản dùng để trình ký.", "Số liệu trong báo cáo cần có nguồn hoặc mốc thời gian."],
    formatProfile: administrativeFormatProfile,
    tags: ["báo cáo", "hành chính", "tổng kết", "sơ kết"],
    priority: 95,
    isOfficialStyleSupported: true,
  },
  {
    id: "administrative_memo",
    name: "Phiếu ghi nhớ hành chính",
    group: "administrative_document",
    category: "memo",
    description: "Khung ghi nhớ nội bộ ngắn, nêu vấn đề, phương án và đề xuất xử lý.",
    useCases: ["Ghi nhớ nội bộ", "Tờ trình ngắn", "Thông tin phục vụ xử lý"],
    requiredInputs: administrativeInputs,
    optionalInputs: [input("options", "Phương án xử lý", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("issue", "section", "Vấn đề cần xử lý", USER_FACING_PLACEHOLDERS.verify), block("basis", "legal_basis", "Căn cứ/thông tin nền", USER_FACING_PLACEHOLDERS.legalBasis), block("options", "list", "Phương án", USER_FACING_PLACEHOLDERS.verify), block("proposal", "section", "Đề xuất", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Nêu rõ người/đơn vị cần xử lý.", "Không dùng số liệu chưa xác minh."],
    formatProfile: administrativeFormatProfile,
    tags: ["memo", "ghi nhớ", "hành chính"],
    priority: 76,
    isOfficialStyleSupported: true,
  },
  {
    id: "official_dispatch_basic",
    name: "Công văn cơ bản",
    group: "administrative_document",
    category: "official_dispatch",
    description: "Khung công văn có kính gửi, căn cứ/nội dung, đề nghị và nơi nhận.",
    useCases: ["Công văn đề nghị", "Công văn trao đổi", "Công văn hướng dẫn"],
    requiredInputs: administrativeInputs,
    optionalInputs: [input("request", "Nội dung đề nghị", USER_FACING_PLACEHOLDERS.verify), input("deadline", "Thời hạn", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("recipients", "recipients", "Kính gửi", USER_FACING_PLACEHOLDERS.recipient), block("basis", "legal_basis", "Căn cứ/nội dung liên quan", USER_FACING_PLACEHOLDERS.legalBasis), block("request", "section", "Nội dung đề nghị", USER_FACING_PLACEHOLDERS.verify), block("closing", "paragraph", "Kết thúc công văn", USER_FACING_PLACEHOLDERS.verify), block("signature", "signature", "Ký tên", USER_FACING_PLACEHOLDERS.verify, undefined, false)],
    preflightHints: ["Kiểm tra đúng tên cơ quan nhận văn bản.", "Căn cứ pháp lý cần chính xác trước khi phát hành."],
    formatProfile: administrativeFormatProfile,
    tags: ["công văn", "đề nghị", "kính gửi"],
    priority: 92,
    isOfficialStyleSupported: true,
  },
  {
    id: "work_plan",
    name: "Kế hoạch công việc",
    group: "administrative_document",
    category: "work_plan",
    description: "Khung kế hoạch gồm mục tiêu, nhiệm vụ, tiến độ, phân công và nguồn lực.",
    useCases: ["Kế hoạch triển khai", "Kế hoạch công tác", "Phân công nhiệm vụ"],
    requiredInputs: administrativeInputs,
    optionalInputs: [input("timeline", "Tiến độ", USER_FACING_PLACEHOLDERS.verify), input("resources", "Nguồn lực", USER_FACING_PLACEHOLDERS.data)],
    layoutBlocks: [titleBlock, block("purpose", "section", "Mục đích, yêu cầu", USER_FACING_PLACEHOLDERS.verify), block("tasks", "table", "Bảng nhiệm vụ, tiến độ", USER_FACING_PLACEHOLDERS.data), block("assignment", "section", "Tổ chức thực hiện", USER_FACING_PLACEHOLDERS.verify), sourceBlock],
    preflightHints: ["Bảng nhiệm vụ cần có đơn vị phụ trách và thời hạn.", "Nguồn lực/số liệu cần được bổ sung nếu còn trống."],
    formatProfile: administrativeFormatProfile,
    tags: ["kế hoạch", "tiến độ", "phân công"],
    priority: 90,
    isOfficialStyleSupported: true,
  },
  {
    id: "meeting_minutes",
    name: "Biên bản họp",
    group: "administrative_document",
    category: "meeting_minutes",
    description: "Khung biên bản ghi thời gian, thành phần, nội dung thảo luận và kết luận.",
    useCases: ["Biên bản họp", "Biên bản làm việc", "Ghi nhận kết luận"],
    requiredInputs: [input("meetingTitle", "Tên/cuộc họp", USER_FACING_PLACEHOLDERS.title), input("timePlace", "Thời gian, địa điểm", USER_FACING_PLACEHOLDERS.verify), input("participants", "Thành phần tham dự", USER_FACING_PLACEHOLDERS.verify)],
    optionalInputs: [input("conclusions", "Kết luận/nhiệm vụ", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("time_place", "metadata", "Thời gian, địa điểm", USER_FACING_PLACEHOLDERS.verify), block("participants", "list", "Thành phần tham dự", USER_FACING_PLACEHOLDERS.verify), block("discussion", "section", "Nội dung trao đổi", USER_FACING_PLACEHOLDERS.verify), block("conclusions", "table", "Kết luận và nhiệm vụ", USER_FACING_PLACEHOLDERS.verify), block("signature", "signature", "Chữ ký xác nhận", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Kiểm tra đủ thành phần tham dự và người chủ trì.", "Nhiệm vụ cần có người phụ trách và thời hạn nếu có."],
    formatProfile: administrativeFormatProfile,
    tags: ["biên bản", "họp", "kết luận"],
    priority: 88,
    isOfficialStyleSupported: true,
  },
  {
    id: "notice_basic",
    name: "Thông báo cơ bản",
    group: "administrative_document",
    category: "notice",
    description: "Khung thông báo nêu nội dung, đối tượng áp dụng, thời gian và yêu cầu thực hiện.",
    useCases: ["Thông báo", "Thông tin triển khai", "Yêu cầu thực hiện"],
    requiredInputs: administrativeInputs,
    optionalInputs: [input("effectiveDate", "Thời gian áp dụng", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("recipients", "recipients", "Đối tượng nhận thông báo", USER_FACING_PLACEHOLDERS.recipient), block("content", "section", "Nội dung thông báo", USER_FACING_PLACEHOLDERS.verify), block("implementation", "section", "Yêu cầu thực hiện", USER_FACING_PLACEHOLDERS.verify), block("signature", "signature", "Ký tên", USER_FACING_PLACEHOLDERS.verify, undefined, false)],
    preflightHints: ["Nêu rõ thời gian hiệu lực nếu có.", "Không bỏ sót đối tượng cần nhận thông báo."],
    formatProfile: administrativeFormatProfile,
    tags: ["thông báo", "triển khai", "yêu cầu"],
    priority: 82,
    isOfficialStyleSupported: true,
  },
  {
    id: "summary_sheet",
    name: "Phiếu tổng hợp",
    group: "administrative_document",
    category: "summary_sheet",
    description: "Khung phiếu tổng hợp ngắn có vấn đề, thông tin chính, số liệu và kiến nghị.",
    useCases: ["Phiếu tổng hợp", "Tóm tắt phục vụ lãnh đạo", "Tổng hợp nguồn"],
    requiredInputs: [input("topic", "Vấn đề tổng hợp", USER_FACING_PLACEHOLDERS.verify), input("sources", "Nguồn tổng hợp", USER_FACING_PLACEHOLDERS.source)],
    optionalInputs: [input("data", "Số liệu chính", USER_FACING_PLACEHOLDERS.data), input("recommendation", "Kiến nghị", USER_FACING_PLACEHOLDERS.verify)],
    layoutBlocks: [titleBlock, block("summary", "lead", "Tóm tắt vấn đề", USER_FACING_PLACEHOLDERS.verify), block("facts", "list", "Thông tin/số liệu chính", USER_FACING_PLACEHOLDERS.data), block("assessment", "section", "Nhận định ngắn", USER_FACING_PLACEHOLDERS.source), block("proposal", "section", "Kiến nghị", USER_FACING_PLACEHOLDERS.verify)],
    preflightHints: ["Nguồn tổng hợp phải được ghi rõ.", "Phần nhận định cần phân biệt với dữ kiện."],
    formatProfile: administrativeFormatProfile,
    tags: ["phiếu tổng hợp", "tóm tắt", "lãnh đạo"],
    priority: 78,
    isOfficialStyleSupported: true,
  },
];

export const getEditorialTemplates = (): EditorialTemplate[] => sortTemplatesByPriority(editorialTemplates);

export const getEditorialTemplateById = (id: string): EditorialTemplate | undefined =>
  editorialTemplates.find((template) => template.id === id);
